services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    working_dir: /app
    command: ["pytest", "tests"]
